/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taqueria;

/**
 *
 * @author ramirohb
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMenu = new javax.swing.JLabel();
        lblTacos = new javax.swing.JLabel();
        lblBebidas = new javax.swing.JLabel();
        lblPastor = new javax.swing.JLabel();
        lblSuadero = new javax.swing.JLabel();
        lblLonganiza = new javax.swing.JLabel();
        lblTripa = new javax.swing.JLabel();
        lblAgua = new javax.swing.JLabel();
        lblRefresco = new javax.swing.JLabel();
        lblPulque = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblMenu.setBackground(new java.awt.Color(153, 204, 255));
        lblMenu.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu.setText("Menu");

        lblTacos.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblTacos.setText("Tacos");

        lblBebidas.setFont(new java.awt.Font("Helvetica Neue", 0, 48)); // NOI18N
        lblBebidas.setText("Bebidas");

        lblPastor.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPastor.setText("Taco de pastor  $7");

        lblSuadero.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblSuadero.setText("Taco de suadero $9");

        lblLonganiza.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblLonganiza.setText("Taco de longaniza $12");

        lblTripa.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblTripa.setText("Taco de tripa $12");

        lblAgua.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblAgua.setText("Agua (horchata y jamaica) $18");

        lblRefresco.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblRefresco.setText("Regresco $15");

        lblPulque.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        lblPulque.setText("Pulque $13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblLonganiza)
                                .addGap(127, 127, 127)
                                .addComponent(lblPulque)
                                .addGap(44, 73, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPastor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblAgua))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTripa)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblSuadero)
                                        .addGap(136, 136, 136)
                                        .addComponent(lblRefresco)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(lblTacos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBebidas)
                        .addGap(24, 24, 24)))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTacos)
                    .addComponent(lblBebidas))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPastor)
                    .addComponent(lblAgua))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSuadero)
                    .addComponent(lblRefresco))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLonganiza)
                    .addComponent(lblPulque))
                .addGap(18, 18, 18)
                .addComponent(lblTripa)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAgua;
    private javax.swing.JLabel lblBebidas;
    private javax.swing.JLabel lblLonganiza;
    private javax.swing.JLabel lblMenu;
    private javax.swing.JLabel lblPastor;
    private javax.swing.JLabel lblPulque;
    private javax.swing.JLabel lblRefresco;
    private javax.swing.JLabel lblSuadero;
    private javax.swing.JLabel lblTacos;
    private javax.swing.JLabel lblTripa;
    // End of variables declaration//GEN-END:variables
}
