/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package taqueria;

/**
 *
 * @author ramirohb
 */
public class TipoPago extends javax.swing.JFrame {

    /**
     * Creates new form TipoPago
     */
    public TipoPago() {
        this.setContentPane(new ImagenFondo2());
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPagoEnLinea = new javax.swing.JLabel();
        lblMetodo = new javax.swing.JLabel();
        RbTarjetaCredito = new javax.swing.JRadioButton();
        RbTarjetaDebito = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblPagoEnLinea.setFont(new java.awt.Font("Sketch 3D", 0, 48)); // NOI18N
        lblPagoEnLinea.setForeground(new java.awt.Color(0, 0, 0));
        lblPagoEnLinea.setText("Pago en linea");

        lblMetodo.setFont(new java.awt.Font("Supersonic Rocketship", 2, 18)); // NOI18N
        lblMetodo.setForeground(new java.awt.Color(0, 0, 0));
        lblMetodo.setText("Selecciona el método de pago: ");

        RbTarjetaCredito.setFont(new java.awt.Font("Supersonic Rocketship", 2, 18)); // NOI18N
        RbTarjetaCredito.setForeground(new java.awt.Color(0, 0, 0));
        RbTarjetaCredito.setText("Tarjeta de crédito");
        RbTarjetaCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbTarjetaCreditoActionPerformed(evt);
            }
        });

        RbTarjetaDebito.setFont(new java.awt.Font("Supersonic Rocketship", 2, 18)); // NOI18N
        RbTarjetaDebito.setForeground(new java.awt.Color(0, 0, 0));
        RbTarjetaDebito.setText("Tarjeta de débito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblPagoEnLinea)
                .addGap(137, 137, 137))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(362, 362, 362)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbTarjetaCredito)
                            .addComponent(RbTarjetaDebito)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblMetodo)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblPagoEnLinea)
                .addGap(87, 87, 87)
                .addComponent(RbTarjetaCredito)
                .addGap(5, 5, 5)
                .addComponent(lblMetodo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(RbTarjetaDebito)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbTarjetaCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbTarjetaCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbTarjetaCreditoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TipoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TipoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TipoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TipoPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TipoPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RbTarjetaCredito;
    private javax.swing.JRadioButton RbTarjetaDebito;
    private javax.swing.JLabel lblMetodo;
    private javax.swing.JLabel lblPagoEnLinea;
    // End of variables declaration//GEN-END:variables
}
